webDevObjects = [
    {
        pageDetails: { pageTitle: "My page", navBarTitle: "Allform Software Solutions", headingText: "My heading", headingClass: "alert alert-info" },
        charts: [
            [
                "r5-c1",
                "My Title",
                "pie",
                30,
                150,
                [
                    [10, 50, 20, 39, 54, 44, 45],
                    [14, 44, 57, 99, 54, 57, 88],
                ],
                ["Dataset 1"],
                [["green", "red", "blue", "orange", "pink", "brown", "purple"]],
                [["gray", "gray", "gray", "gray", "gray", "gray", "gray"]],
                ["Kris", "Ben", "John", "Michle", "James", "Tim", "Ryan"],
                !1,
            ],
            [
                "r5-c2",
                "My Title",
                "horizontalBar",
                30,
                150,
                [
                    [10, 50, 20, 39, 54, 44, 45],
                    [14, 44, 57, 99, 54, 57, 88],
                    [11, 22, 57, 88, 99, 55, 44],
                    [45, 54, 74, 44, 12, 12, 45],
                ],
                ["Dataset 1", "Dataset 2", "Dataset 3", "Dataset 4"],
                [
                    ["green", "green", "green", "green", "green", "green", "green"],
                    ["orange", "orange", "orange", "orange", "orange", "orange", "orange"],
                    ["pink", "pink", "pink", "pink", "pink", "pink", "pink"],
                    ["red", "red", "red", "red", "red", "red", "red"],
                ],
                [
                    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
                    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
                    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
                    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
                ],
                ["Kris", "Ben", "John", "Michle", "James", "Tim", "Ryan"],
                ,
                !1,
            ],
            [
                "r5-c3",
                "My Title",
                "line",
                30,
                150,
                [
                    [10, 50, 20, 39, 54, 44, 45],
                    [14, 44, 57, 99, 54, 57, 88],
                    [11, 22, 57, 88, 99, 55, 44],
                    [45, 54, 74, 44, 12, 12, 45],
                ],
                ["Dataset 1", "Dataset 2", "Dataset 3", "Dataset 4"],
                [
                    ["green", "green", "green", "green", "green", "green", "green"],
                    ["orange", "orange", "orange", "orange", "orange", "orange", "orange"],
                    ["pink", "pink", "pink", "pink", "pink", "pink", "pink"],
                    ["red", "red", "red", "red", "red", "red", "red"],
                ],
                [["green"], ["orange"], ["pink"], ["red"]],
                ["Kris", "Ben", "John", "Michle", "James", "Tim", "Ryan"],
                ,
                !1,
            ],
            [
                "r6-c1",
                "My Title",
                "bar",
                30,
                150,
                [
                    [10, 50, 20, 39, 54, 44, 45],
                    [14, 44, 57, 99, 54, 57, 88],
                    [11, 22, 57, 88, 99, 55, 44],
                    [45, 54, 74, 44, 12, 12, 45],
                ],
                ["Dataset 1", "Dataset 2", "Dataset 3", "Dataset 4"],
                [
                    ["green", "green", "green", "green", "green", "green", "green"],
                    ["orange", "orange", "orange", "orange", "orange", "orange", "orange"],
                    ["pink", "pink", "pink", "pink", "pink", "pink", "pink"],
                    ["red", "red", "red", "red", "red", "red", "red"],
                ],
                [
                    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
                    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
                    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
                    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
                ],
                ["Kris", "Ben", "John", "Michle", "James", "Tim", "Ryan"],
                ,
                !1,
            ],
            [
                "r6-c2",
                "My Title",
                "bar",
                30,
                150,
                [
                    [10, 50, 20, 39, 54, 44, 45],
                    [14, 44, 57, 99, 54, 57, 88],
                    [11, 22, 57, 88, 99, 55, 44],
                    [45, 54, 74, 44, 12, 12, 45],
                ],
                ["Dataset 1", "Dataset 2", "Dataset 3", "Dataset 4"],
                [
                    ["green", "green", "green", "green", "green", "green", "green"],
                    ["orange", "orange", "orange", "orange", "orange", "orange", "orange"],
                    ["pink", "pink", "pink", "pink", "pink", "pink", "pink"],
                    ["red", "red", "red", "red", "red", "red", "red"],
                ],
                [
                    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
                    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
                    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
                    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
                ],
                ["Kris", "Ben", "John", "Michle", "James", "Tim", "Ryan"],
                ,
                !0,
            ],
            [
                "r6-c3",
                "My Title",
                "horizontalBar",
                30,
                150,
                [
                    [10, 50, 20, 39, 54, 44, 45],
                    [14, 44, 57, 99, 54, 57, 88],
                    [11, 22, 57, 88, 99, 55, 44],
                    [45, 54, 74, 44, 12, 12, 45],
                ],
                ["Dataset 1", "Dataset 2", "Dataset 3", "Dataset 4"],
                [
                    ["green", "green", "green", "green", "green", "green", "green"],
                    ["orange", "orange", "orange", "orange", "orange", "orange", "orange"],
                    ["pink", "pink", "pink", "pink", "pink", "pink", "pink"],
                    ["red", "red", "red", "red", "red", "red", "red"],
                ],
                [
                    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
                    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
                    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
                    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
                ],
                ["Kris", "Ben", "John", "Michle", "James", "Tim", "Ryan"],
                ,
                !0,
            ],
        ],
        measures: [
            ["r1-c5", "", "Marked Q1: ", 500, " m", "220", ";background-color:purple;border:purple;color:white;"],
            ["r1-c5", "btn-dark", "Marked Q2: ", 500, " m", "220", ""],
            ["r1-c6", "", "Marked Q3: ", 200, " cm", "220", ";background-color:crimson;border:crimson;color:white;"],
            ["r1-c6", "btn-success", "Marked Q4: ", 500, " m", "220", ""],
            ["r1-c7", "", "Qty: ", 500, " m", "220", ";background-color:purple;border:purple;color:white;"],
            ["r1-c7", "btn-primary", "Qty: ", 500, " m", "220", ""],
            ["r1-c8", "", "Qty: ", 500, " m", "220", ";background-color:orange;border:orange;color:white;"],
            ["r1-c8", "btn-secondary", "Qty: ", 500, " m", "220", ""],
            ["r1-c9", "", "Qty: ", 200, " cm", "220", ";background-color:pink;border:pinkcolor:white;color:white;"],
            ["r1-c9", "btn-warning", "Qty: ", 500, " m", "220", ";color:white;"],
            ["r1-c10", "", "Qty: ", 500, " m", "220", ";background-color:black;border:black;color:white;"],
            ["r1-c10", "btn-info", "Qty: ", 500, " m", "220", ""],
            ["r1-c11", "", "Qty: ", 500, " m", "220", ";background-color:teal;border:teal;color:white;"],
            ["r1-c11", "btn-danger", "Qty: ", 500, " m", "220", ""],
        ],
        navBar: [
            [["Heading 1", "Heading 2"]],
            [
                ["Heading 1 Link 1", "#"],
                ["Heading 1 Link 2", "#"],
            ],
            [
                ["Heading 2 Link 1", "#"],
                ["Heading 2 Link 2", "#"],
            ],
        ],
        tables: [
            ["r3-c1", ["table table-hover", "yes", 49.8, "padding:10px", "item "], ["Name", "Age", "Gender", "DoB"], ["Kris", "36", "M", "12/3/1990"], ["Tim", "28", "M", "4/12/1987"], ["Jane", "32", "F", "3/10/200"]],
            ["r3-c2", ["table table-dark table-hover", "no", 49.8, "padding:10px", "item "], ["Name", "Age", "Gender", "DoB"], ["Kris", "36", "M", "12/3/1990"], ["Tim", "28", "M", "4/12/1987"], ["Jane", "32", "F", "3/10/200"]],
        ],
        text: [
            [
                "r7-c1",
                100,
                400,
                "margin-left:0%; text-align:left;",
                "center",
                '<div class=\'item\'>\n\t\t\t\t<h1 class="">Excel Web Development Add-In</h1>\n\t\t\t\t<p>\n\t\t\t\t  Below are numerious tools to assist with the Excel Web Development Add-in.\n\t\t\t\t  <br>\n\t\t\t\t  <a href="">Download</a> - <a href="#">Documentation</a>\n\t\t\t\t</p>\n\t\t\t\t<table>\n\t\t\t\t  <tbody><tr>\n\t\t\t\t\t<td>\n\t\t\t\t\t  <p>\n\t\t\t\t\t\t</p><h4>Examples:</h4>\n\t\t\t\t\t\t<ul>\n\t\t\t\t\t\t  <li>\n\t\t\t\t\t\t\t<a href="#">Resume</a>\n\t\t\t\t\t\t  </li>\n\t\t\t\t\t\t  <li>\n\t\t\t\t\t\t\t<a href="#">Artical</a>\n\t\t\t\t\t\t  </li>\n\t\t\t\t\t\t  <li>\n\t\t\t\t\t\t\t<a href="#">Dashboard</a>\n\t\t\t\t\t\t  </li>\n\t\t\t\t\t\t  <li>\n\t\t\t\t\t\t\t<a href="#">Profile</a>\n\t\t\t\t\t\t  </li>\n\t\t\t\t\t\t  <li>\n\t\t\t\t\t\t\t<a href="#">Navigation</a>\n\t\t\t\t\t\t  </li>\n\t\t\t\t\t\t  <li>\n\t\t\t\t\t\t\t<a href="#">Invite</a>\n\t\t\t\t\t\t  </li>\n\t\t\t\t\t\t  <li>\n\t\t\t\t\t\t\t<a href="#">Information</a>\n\t\t\t\t\t\t  </li>\n\t\t\t\t\t\t</ul>\n\t\t\t\t\t  <p></p>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td style="padding-left:80px; padding-top: 0px; vertical-align:top;width:300px;">\n\t\t\t\t\t  <p>\n\t\t\t\t\t\t</p><h4>Documentation:</h4>\n\t\t\t\t\t\t<ul>\n\t\t\t\t\t\t  <li>\n\t\t\t\t\t\t\t<a href="#">Overview</a>\n\t\t\t\t\t\t  </li>\n\t\t\t\t\t\t  <li>\n\t\t\t\t\t\t\t<a href="#">Text</a>\n\t\t\t\t\t\t  </li>\n\t\t\t\t\t\t  <li>\n\t\t\t\t\t\t\t<a href="#">Tables</a>\n\t\t\t\t\t\t  </li>\n\t\t\t\t\t\t  <li>\n\t\t\t\t\t\t\t<a href="#">Blur Filters</a>\n\t\t\t\t\t\t  </li>\n\t\t\t\t\t\t  <li>\n\t\t\t\t\t\t\t<a href="#">Images</a>\n\t\t\t\t\t\t  </li>\n\t\t\t\t\t\t  <li>\n\t\t\t\t\t\t\t<a href="#">Charts</a>\n\t\t\t\t\t\t  </li>\n\t\t\t\t\t\t  <li>\n\t\t\t\t\t\t\t<a href="#">Metrics</a>\n\t\t\t\t\t\t  </li>\n\t\t\t\t\t\t</ul>\n\t\t\t\t\t  <p></p>\n\t\t\t\t\t</td>\n\t\t\t\t  </tr>\n\t\t\t\t</tbody></table>\n\t\t\t\t</div>\n\t\t\t',
            ],
        ],
        iframe: [["r8-c1", 100, 500, "margin-top:50px; text-align:left;", "center", "no", "https://kjtakke.github.io/", "hidden", 0]],
        images: [["r9-c1", 30, , "margin-top:50px; text-align:left;", "center", "https://kjtakke.github.io/images/background/Blue-Clouds.jpg"]],
    },
];
